config/routes.rb
CapstoneHonda::Application.routes.draw do
  
  resources :dpms
  resources :properties
  resources :password_resets
  resources :testfiles
  
  match '/testfiles/download', :controller => 'testfiles', :action => 'download', via: 'get'
  match '/materials/download', :controller => 'materials', :action => 'download', via: 'get'
  match '/signup', to: 'users#new',           via: 'get'
  match '/signin', to: 'sessions#new',        via: 'get'
  match '/signout',to: 'sessions#destroy',    via: 'delete'
  match '/help',   to: 'static_pages#help',   via: 'get'
  match '/about_path',  to: 'static_pages#about',  via: 'get'
  match '/contact',  to: 'static_pages#contact',  via: 'get'
  match '/users',  to: 'users#index',  via: 'get'
  match '/users/join_group', :controller => 'users', :action => 'join_group', via: 'get'
  match '/users/accept_membership', :controller => 'users', :action => 'accept_membership', via: 'get'

  match '/step1', to: 'dpms#step1', via: 'patch'
  match '/step1', to: 'dpms#step1', via: 'put'
  match '/step1', to: 'dpms#step1', via: 'get'
  match '/step2', to: 'dpms#step2', via: 'patch'
  match '/step2', to: 'dpms#step2', via: 'put'

  match '/step3', to: 'dpms#step3', via: 'patch'
  match '/step3', to: 'dpms#step3', via: 'put'

  match '/step4', to: 'dpms#step4', via: 'patch'
  match '/step4', to: 'dpms#step4', via: 'put'

  resources :materials do
    get :reset_filterrific, :on => :collection
  end

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  root 'static_pages#home'
 
 

  

end

app/models/dpm.rb
class Dpm < ActiveRecord::Base
	mount_uploader :filename, DpmFileUploader
	attr_accessible :filename, :graph_number, :youngs_modulus, :id, :gauge_length, :necking_point, :fitting_param, :threshold
end

app/controllers/dpms_controller.rb
class DpmsController < ApplicationController
  before_action :set_dpm, only: [:show, :edit, :update, :destroy, :step1, :step2, :step3, :step4]
  helper DpmsHelper

  # GET /dpms
  # GET /dpms.json
  def index
    @dpm = Dpm.all
  end

  # GET /dpms/1
  # GET /dpms/1.json
  def show
  end

  # GET /dpms/new
  def new
  	@dpm = Dpm.new
  end

  # GET /dpms/1/edit
  def edit
  end

  # POST /dpms
  # POST /dpms.json
  def create
  	@dpm = Dpm.new(dpm_params)
  	#todo @user = User.find_by(current_user[:id])
  	#@user.dpms << @dpm
  	
    respond_to do |format|
      if @dpm.save
        format.html { render '/dpms/step1', notice: 'Dpm was successfully created.' }
        format.json { render action: 'show', status: :created, location: @dpm }
      else
        format.html { render action: 'new' }
        format.json { render json: @dpm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dpms/1
  # PATCH/PUT /dpms/1.json
  def update
    respond_to do |format|
      if @dpm.update(dpm_params)  
        format.html { render '/dpms/step1', notice: 'Dpm was successfully updated.' }
        format.json { head :no_content }  
      else
        format.html { render action: 'edit' }
        format.json { render json: @dpm.errors, status: :unprocessable_entity }
      end
    end
  end

  def step1
    respond_to do |format|
      if @dpm.update(dpm_params)
        format.html { render '/dpms/step2', notice: 'Change this to something else'}
        format.json { head :no_content }
      else
        format.html { render '/dpms/step1', notice: 'Step not saved, please retry'}
        format.html { render json: @dpm.errors, status: :unprocessable_entity}
      end
    end
  end

  def step2
    respond_to do |format|
      if @dpm.update(dpm_params)
        format.html { render '/dpms/step3', notice: 'Change me'}
        format.json { head :no_content }
      else
        format.html { render '/dpms/step2', notice: 'Step not saved, please retry'}
        format.html { render json: @dpm.errors, status: :unprocessable_entity}
      end
    end
  end

  def step3
    respond_to do |format|
      if @dpm.update(dpm_params)
        format.html { render '/dpms/step4', notice: 'Change me'}
        format.json { head :no_content }
      else
        format.html { render '/dpms/step3', notice: 'Step not saved, please retry'}
        format.html { render json: @dpm.errors, status: :unprocessable_entity}
      end
    end
  end

  def step4
    respond_to do |format|
      if @dpm.update(dpm_params)
        format.html { render '/dpms/step5', notice: 'Change me'}
        format.json { head :no_content }
      else
        format.html { render '/dpms/step4', notice: 'Step not saved, please retry'}
        format.html { render json: @dpm.errors, status: :unprocessable_entity}
      end
    end
  end


  # DELETE /dpms/1
  # DELETE /dpms/1.json
  def destroy
    @dpm.destroy
    respond_to do |format|
      format.html { redirect_to dpms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dpm
      @dpm = Dpm.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def dpm_params
      params.require(:dpm).permit(:filename, :graph_number, :youngs_modulus, :gauge_length, :necking_point, :fitting_param, :threshold)     end
  end

app/helpers/dpms_helper.rb
module DpmsHelper
	include Math
	#used to create a set of graphs for the dpm to show
	#the user picks one graph for the dpm process
	def create_hash(filename)
		graphs = [] #array of all graphs
		graph = [] #array of points
		point = [] #points
		hash = {}
		noYcolumns = 0
		file = File.open(filename, 'r')
		while !file.eof?
			line = file.readline
			line = line.split(",").collect {|x| x.strip}
			noYcolumns = line.length-1
			for t in 0...noYcolumns #iterate over Y columns in row
				point[t] = [line[0].to_f, line[t+1].to_f] #get x,y1/2/3/...; save in point	
				graph.push(point[t]) #store each point in a graph
			end
			graphs.push(graph) #store graph created in graphs array
			graph = [] #clear the graph array
		end
		#graphs.length = num rows, graphs[i].length = num cols
		for i in 0...noYcolumns #for each column i
			for j in 0...graphs.length #for each row j
				hash.store(graphs[j][0][0], graphs[j][i][1]) #let x point to y1/2/3/...
			end
			graph[i] = hash
			hash = {}
		end
		file.close
		graph
	end

	#returns the last point in the hash
	#takes a hash as input 
	def getLastPoint myhash
			#sort the hash and get the x values
			dummy = myhash.keys.sort
			#save the x value of the last point 
			xval = dummy.last
			#get the y value of the last point
			yval = myhash[xval]
			return [xval, yval]
	end

	def getMaxMin(graph)
		dummy=[]
		dummy[0]=graph.values.max
		dummy[1]=graph.values.min
		dummy
	end


# 	tstrain=log(1+strain); tstress=stress.*(1+strain);
# %Subtract out elastic region of curve
# pstrain=tstrain-(tstress./E);

	#this functions returns the tstrain (array) 
	#and pstrain vs tstress (hash) values
	#trial is a hash 
	#youngs is youngs modulus to calculate tstress
	#the return value is a hash [tstrain pstrainvststress]
	def tp_strain trial, youngs
		tstrain = Array.new
		pstrain = Hash.new
		trial.each do |key, value| 
			#change stress values first (y values)
			new_value = value * (1 + key)
			#change the strain values to tstrain values
			new_key = Math.log(1 + key)
			#add the tstrain values to the array
			tstrain << new_key
			#change the tstrain to pstrain
			new_key = new_key - (new_value / (youngs * 1000))
			pstrain.store(new_key, new_value)
		end
		return [tstrain, pstrain]
	end	

	def rounder graph, precision
		adam = Hash.new
		graph.each do | key, value |
			new_key = key.round(precision)
			adam.store(new_key, value)
		end
		adam
	end

	def deriv trial
		dummy = Hash.new
		trial.sort
		puts "trial key: ", trial.keys
		keys = trial.keys
		puts "keys: ", keys
		values = trial.values
		#getting derivative minus first and last points
		for i in 1...keys.length - 2
			derivy_val = (values[i + 1] - values[i]) / (keys[i + 1] - keys[i])
			dummy.store(keys[i], derivy_val )
		end
		dummy
	end

	def intersection trial, derivative, thresh
		dummy = Hash.new
		trial.each do |key, value|
			deriv_val = 0.0
			if derivative.key?(key)
				deriv_val = derivative[key]
			end
			#compare the value in trial with deriv
			if (((value - deriv_val).abs / value) < thresh)
				dummy.store(key, value)
			end
		end
		dummy
	end
	#end
	# Returns the value of f(x)
	# f(x) = (a+x)/(b+x))^(b+x) - c/d
	def equationValue(a, b, c, d, x)
		f = ((a+x)/(b+x))**(b + x)
		f = f - (c/d)
		return f
	end

	# This is for checking that we're working with the right side of our asymptope
	# The point is to give more accurate error message
	def isLeftSideOfAsymptote(a, b, c, d)
		hasError = false

		f1 = E**(a-b)
		f2 = c/d
		
		if (f1 < f2)
			hasError = true
	    end

	    #puts "f1 = " + f1.to_s
	    #puts "c/d = " + f2.to_s
	    #puts "hasError = " + hasError.to_s

		return hasError
	end

	def solve(a, b, c, d)
		p=0.0
		q=200.0
		errorV=0.00001

		if isLeftSideOfAsymptote(a, b, c, d)
			puts "Data error:  should not produce negative eps_o."
			return nil
		end

		fp = equationValue(a, b, c, d, p)
		fq = equationValue(a, b, c, d, q)

		# This is checking if there's a root (eps_o) can be found
	    if fp > 0
	    	puts "No roots found"
	    	return nil
	    end

		# Ensure fp and fq have different signs, in order to guarantee
		# that a root will be found between them
		while !(fp * fq < 0) do
			q = q * 2
		    fq = equationValue(a, b, c, d, q)
		end
		
		midpoint = (q + p) / 2
	    fMidpoint = equationValue(a, b, c, d, midpoint)

		while !(fMidpoint.abs < errorV) do
			if fp * fMidpoint < 0
				q = midpoint
			    fq = equationValue(a, b, c, d, q)
			else
				p = midpoint
			    fp = equationValue(a, b, c, d, p)
			end

			midpoint = (q + p) / 2
			fMidpoint = equationValue(a, b, c, d, midpoint)
		end
		
	    return midpoint
	end

	#this function will return the swift coefficients
	#these are needed to create the final output
	#the output of this function is [eps_o, n, k]
	def getSwifts epsPF, epsPN, sigF, sigN
	    rtn = Array.new
	    #first get eps_o using the solver
	    eps_o = solve(epsPF, epsPN, sigF, sigN)
	    rtn << eps_o
	    #back solve for n
	    n = eps_o + epsPN
	    rtn << n
	    #back solve for k
	    k = sigF / ((eps_o + epsPF)**n)
	    rtn << k
	    rtn
	end

	#this function will remove all key/value pairs in 
	#the hash where the key is greater than xval
	#the return is a hash of only key/value pairs 
	#that satisfy this condition
	def removePastX myhash, xval
		rtn = Hash.new
		myhash.each do |key, value|
			if key < xval
				rtn.store(key, value)
			end	
		end
		rtn
	end

	#make sure that all of these values make sense
	#TODO: test the output
	def getSystemVars stress, pstress, tstrain, hardstress, neckingpoint, gauge, fitparam, youngs
		#get the index of the last point 
		neckindex = hardstress.length - 1
		df = getLastPoint(pstrain)[0]
		dn = tstrain.sort[neckindex]
		sigma_n = pstress[neckingpoint]
		laststresspoint = getLastPoint(stress)
		sigma_ef = laststresspoint[1]
		eps_en = laststresspoint[0]
		df_dn = ((E**df) * gauge) - ((E**dn) *gauge)
		eps_f = Math.log(eps_en + 1 + (df_dn/fitparam))
		sigma_f = sigma_ef * (eps_en + 1 + (df_dn/fitparam))
		eps_pf = eps_f - (sigma_f/youngs)
		return [eps_pf, neck, sigma_f, sigma_n]
		
	end
	#remove all points after the necking point
	#eps_pn = x value pstrain at necking point (this is our necking point attr)
	#df = last pstrain value (x)
	#dn = tstrain necking point (x)
	#sigma_n is tstress at necking point (y)
	#TODO separate TSTRESS and PSTRESS functions
	#sigma_ef = stress (y) at last point (normal graph)
	#eps_en = strain (x) at last point (normal graph)

	#hardstress/strain is graph after removing past necking point
	#df_dn = ((E**df) * gaugelength) - ((E**dn) *gaugelength)
	
	#eps_f = Math.log(eps_en + 1 + (df_dn)/fittingparam
	#sigma_f = sigma_ef * (eps_en + 1 + (df_dn)/fittingparam)
	#eps_pf = eps_f - (sigma_f/youngsmod)

	#plus = fittingparam*(1+(accuracy/100))
	#minus = fittingparam*(1-(accuracy/100))

	#get two sets of new values for eps_f, sigma_f, eps_pf (plus/minus)
	#solve the system of equations 3 times
	def createSwiftPoints firstX, totalpoints, currentsize, swiftsco
		#we want evenly spaced points and their corresponding swift values
		rtn = Hash.new
		#get the spacing for the x values 
		spacing = (1 - firstX) / (totalpoints - currentsize)
		for i in 0..(totalpoints - currentsize)
			#create a series of equally spaced points using swift equation as y's
			#y = k * (eps_o + x)**n
			xval = firstX + (i * spacing)
			yval = swiftsco[2] * (swiftsco[0] + xval)**swiftsco[1]
			rtn.store(xval, yval)
		end
		rtn
	end


	#this function returns the necking index

end
	#create (500 - size) more points, equally spaced x's
	    #starting at the end of hardstress graph
	#use the k's, n's, eps_o's from above to get three graphs
	#use the x points generated creating the line values
	#and swifts equation for all three graphs where:
	#y = k * (eps_o + x)**n
	#join hardstress with the swift values for the final output values

app/views/dpms/_form.html.erb
<%= form_for(@dpm) do |f| %>
  <% if @dpm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dpm.errors.count, "error") %> prohibited this dpm from being saved:</h2>

      <ul>
      <% @dpm.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 
  <div class="field">
  	<%= f.label :filename %><br>
    <%= f.file_field :filename %>
  </div>


  <div class="actions">
    <%= f.submit  %>
  </div>
<% end %>

app/views/dpms/edit.html.erb
<h1>Change Input File</h1>

<%= form_for(@dpm, :url => dpm_path(:id => @dpm.id), :method => 'put') do |f| %>
  <% if @dpm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dpm.errors.count, "error") %> prohibited this dpm from being saved:</h2>

      <ul>
      <% @dpm.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 
  <div class="field">
  	<%= f.label :filename %><br>
    <%= f.file_field :filename %>
  </div>


  <div class="actions">
    <%= f.submit "Change Input File" %>
  </div>
<% end %>

app/views/dpms/index.html.erb
<h1>Listing dpms</h1>

<table>
  <thead>
    <tr>
      <th>Show|</th>
      <th>Edit|</th>
      <th>Delete</th>
    </tr>
    <tr>
    	<td></td>
    	<td></td>
    	<td></td>
		</tr>
  </thead>

  <tbody>
    <% @dpm.each do |dpm| %>
      <tr>
        <td><%= link_to 'Show', dpm %></td>
        <td><%= link_to 'Edit', edit_dpm_path(dpm) %></td>
        <td><%= link_to 'Delete', dpm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dpm', new_dpm_path %>

app/views/dpms/new.html.erb
<h1>DPM Process</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/dpms/show.html.erb
<strong>Filename:</strong>
<p>
<%= @dpm.filename %>
<%= link_to File.basename(@dpm.filename.url), @dpm.filename_url %>
<% graph = create_hash(Rails.root.to_s.concat("/public").concat(@dpm.filename.url))%>
<%= line_chart graph.map.with_index {|ea, i| {:name => i+1, :data => ea}}, {discrete: true, library: {pointSize: 0, title: "Plotted Graphs"}} %>
</p>

<%= link_to 'Edit', edit_dpm_path(@dpm) %> |
<%= link_to 'Back', dpms_path %>

app/views/dpms/step1.html.erb
<p>
<% graph = create_hash(Rails.root.to_s.concat("/public").concat(@dpm.filename.url)) %>
<%= line_chart graph.map.with_index {|ea, i| {:name => i+1, :data => ea}}, {discrete: true, library: {pointSize: 0, title: "Plotted Graphs"}} %>
</p>


<%= form_for(@dpm, :url => step1_path(:id => @dpm.id), :method => 'put') do |f| %>
  <% if @dpm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dpm.errors.count, "error") %> prohibited this dpm from being saved:</h2>

      <ul>
      <% @dpm.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
  	<%= f.label :graph_number %><br>
    <%= f.number_field :graph_number %>
  </div>
  <div class="field">
    <%= f.label :youngs_modulus %><br>
    <%= f.number_field :youngs_modulus %>
  </div>
  <div class="field">
    <%= f.label :gauge_length %><br>
    <%= f.number_field :gauge_length %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Change input file', edit_dpm_path(@dpm) %> |
<%= link_to 'Back', dpms_path %>

app/views/dpms/step2.html.erb
<!--process: 
-create hash and get the graph number (-1) to show one graph
-calculate Tstress, Tstrain, Pstrain 
-plot Tstress, pstrain and its derivative 
-have the user select a necking point
-->
<% graph = create_hash(Rails.root.to_s.concat("/public").concat(@dpm.filename.url)) %>
<% trial = Marshal.load(Marshal.dump(graph[@dpm.graph_number - 1])) %>
<% graph = []%>
<% new_trial = rounder(tp_strain(trial, @dpm.youngs_modulus)[1], 4) %>
<% maxMin = getMaxMin(new_trial) %>
<% derivative = deriv(new_trial) %>
<% graph << new_trial %>
<% graph << derivative %>
<% intersections = intersection(new_trial, derivative, 0.2)%>
<strong>STEP 2: Choose a Necking Point</strong>
<p>
<%= line_chart graph.map.with_index {|ea, i| {:name => i+1, :data => ea}}, {discrete: true, library: {pointSize: 0, title: "Tstress vs. Pstrain", vAxis: { viewWindow:{ max:maxMin[0]*1.1, min:maxMin[1]}}}}%>
</p>

<%= form_for(@dpm, :url => step2_path(:id => @dpm.id), :method => 'put') do |f| %>
  <% if @dpm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dpm.errors.count, "error") %> prohibited this dpm from being saved:</h2>

      <ul>
      <% @dpm.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>Recommended Necking Points</p>
<p></p>
  <p><%= intersections %></p>
  <div class="field">
  	<%= f.label :necking_point %><br>
    <%= f.number_field :necking_point, :step => 'any' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Edit', edit_dpm_path(@dpm) %> |

<!-- TODO: have links going to the right places -->

app/views/dpms/step3.html.erb
<!--process: 
-create hash and get the graph number (-1) to show one graph
-calculate Tstress, Tstrain, Pstrain 
-get hardstress/hardstrain points
-graph hardstress/hardstrain -> pre-necking hardening curve
-get fitting paramater and threshold
-->
<% graph = create_hash(Rails.root.to_s.concat("/public").concat(@dpm.filename.url)) %>
<% trial = graph[@dpm.graph_number - 1] %>
<% new_trial = rounder(tp_strain(trial, @dpm.youngs_modulus)[1], 4) %>
<% maxMin = getMaxMin(new_trial) %>
<% hardstress = removePastX(new_trial, @dpm.necking_point)%>


<strong>STEP 3: Hard Stress/Strain</strong>
<p>
<%= line_chart hardstress, {discrete: true, library: {pointSize: 0, title: "Hardening Curve"}} %>
</p>

<%= form_for(@dpm, :url => step3_path(:id => @dpm.id), :method => 'put') do |f| %>
  <% if @dpm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dpm.errors.count, "error") %> prohibited this dpm from being saved:</h2>

      <ul>
      <% @dpm.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
  	<%= f.label :fitting_param %><br>
    <%= f.number_field :fitting_param , :step => 'any'%>
  </div>
  <div class="field">
    <%= f.label :threshold %><br>
    <%= f.number_field :threshold, :step => 'any' %>
  </div>
   <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Edit', edit_dpm_path(@dpm) %> |
<%= link_to 'Back', dpms_path %>

app/views/dpms/step4.html.erb
<!--process: 
-create hash and get the graph number (-1) to show one graph
-calculate Tstress, Tstrain, Pstrain 
-get hardstress/hardstrain points
-get all values needed to solve system of equations (calculated) 
-solve for the 3 sets of systems 
-plot these 3 final graphs once they are calculated
-->
<% graph = create_hash(Rails.root.to_s.concat("/public").concat(@dpm.filename.url)) %>
<% trial = graph[@dpm.graph_number - 1] %>
<% new_trial = rounder(tp_strain(trial, @dpm.youngs_modulus)[1], 4) %>
<% maxMin = getMaxMin(new_trial) %>
<% hardstress = removePastX(new_trial, @dpm.necking_point)%>





<strong>STEP 4:Filename:</strong>
<p>
<%= line_chart graph.map.with_index {|ea, i| {:name => i+1, :data => ea}}, {discrete: true, library: {pointSize: 0, title: "Hardening Curve"}} %>
</p>



<%= link_to 'Edit', edit_dpm_path(@dpm) %> |
<%= link_to 'Back', dpms_path %>

app/views/dpms/step5.html.erb
<!--process: 
-create hash and get the graph number (-1) to show one graph
-calculate Tstress, Tstrain, Pstrain 
-get hardstress/hardstrain points
-graph hardstress/hardstrain -> pre-necking hardening curve
-get fitting paramater and threshold
-->
<% graph = create_hash(Rails.root.to_s.concat("/public").concat(@dpm.filename.url)) %>
<% trial = graph[@dpm.graph_number - 1] %>




<strong>STEP 5:Filename:</strong>
<p>
<%= line_chart graph.map.with_index {|ea, i| {:name => i+1, :data => ea}}, {discrete: true, library: {pointSize: 0, title: "Hardening Curve"}} %>
</p>

<%= form_for(@dpm, :url => step3_path(:id => @dpm.id), :method => 'put') do |f| %>
  <% if @dpm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dpm.errors.count, "error") %> prohibited this dpm from being saved:</h2>

      <ul>
      <% @dpm.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
  	<%= f.label :fitting_param %><br>
    <%= f.number_field :fitting_param %>
  </div>
  <div class="field">
    <%= f.label :threshold %><br>
    <%= f.number_field :threshold %>
  </div>
   <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Edit', edit_dpm_path(@dpm) %> |
<%= link_to 'Back', dpms_path %>