config/routes.rb
CapstoneHonda::Application.routes.draw do
  
  resources :dpms
  resources :properties
  resources :password_resets
  resources :testfiles
  
  match '/testfiles/download', :controller => 'testfiles', :action => 'download', via: 'get'
  match '/materials/download', :controller => 'materials', :action => 'download', via: 'get'
  match '/signup', to: 'users#new',           via: 'get'
  match '/signin', to: 'sessions#new',        via: 'get'
  match '/signout',to: 'sessions#destroy',    via: 'delete'
  match '/help',   to: 'static_pages#help',   via: 'get'
  match '/about_path',  to: 'static_pages#about',  via: 'get'
  match '/contact',  to: 'static_pages#contact',  via: 'get'
  match '/users',  to: 'users#index',  via: 'get'
  match '/users/join_group', :controller => 'users', :action => 'join_group', via: 'get'
  match '/users/accept_membership', :controller => 'users', :action => 'accept_membership', via: 'get'

  match '/step1', to: 'dpms#step1', via: 'patch'
  match '/step1', to: 'dpms#step1', via: 'put'
  match '/step1', to: 'dpms#step1', via: 'get'
  match '/step2', to: 'dpms#step2', via: 'patch'
  match '/step2', to: 'dpms#step2', via: 'put'

  match '/step3', to: 'dpms#step3', via: 'patch'
  match '/step3', to: 'dpms#step3', via: 'put'

  match '/step4', to: 'dpms#step4', via: 'patch'
  match '/step4', to: 'dpms#step4', via: 'put'

  resources :materials do
    get :reset_filterrific, :on => :collection
  end

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  root 'static_pages#home'
 
 

  

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :check_access, only: [:index, :edit, :update, :create, :new, :destroy]
  before_action :for_show, only: [:show]

  # GET /groups
  # GET /groups.json
  def index
    if is_admin?
    	@groups = Group.all
    else
	@groups = Group.where(:owner_name => current_user.name)
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
	@testfiles = Testfile.where(:groupname => @group.groupname)
	
	@mats = MatMembership.where(:group_name => @group.groupname).pluck(:mat_name)
	@materials = Material.where(:mat_name => @mats)
	
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end
  

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @group }
      else
        format.html { render action: 'new' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end	
    @membership = Membership.new(:user_id=>current_user.id, :group_id=>@group.id, :owner=>true, :is_confirmed=>true)
    @membership.save
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to current_user }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:groupname, :description, :owner_email, :owner_id, :is_public, :owner_name)
    end
    
    def check_access
	if not (is_admin? or is_group_admin?)
		if signed_in?
			redirect_to(current_user, :notice => "You tried to access a wrong link, please try again!")
		else
			redirect_to(root, :notice => "You tried to access a wrong link, please try again!")
		end
	end
    end

    def for_show
	@user_memberships = Membership.where(:group_id => @group.id, :user_id => current_user.id, :is_confirmed => true)
	if (@user_memberships.count == 0) and not (is_admin? or is_group_admin?)
		redirect_to(current_user, :notice => "You have to be a member of that group!")
	end
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :groupname %><br>
    <%= f.text_field :groupname %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :owner_name %><br>
    <%= f.text_field :owner_name, :value => current_user.name %>
  </div>
  <div class="field">
    <%= f.label :owner_email %><br>
    <%= f.text_field :owner_email, :value => current_user.email %>
  </div>
  <div class="field">
    <%= f.label :owner_id %><br>
    <%= f.text_field :owner_id , :value => current_user.id %>
    
  </div>
  <div class="field">
    <%= f.label :is_public %><br>
    <%= f.check_box :is_public %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>

<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Groupname</th>
      <th>Description</th>
      <th>Owner name</th>
      <th>Owner email</th>
      <th>Owner ID</th>
      <th>Is public</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.groupname %></td>
        <td><%= group.description %></td>
	<td><%= group.owner_name %></td>
        <td><%= group.owner_email %></td>
        <td><%= group.owner_id %></td>
        <td><%= group.is_public %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<div class="jumbotron">
<p id="notice"><%= notice %></p>

<p>
  <strong>Groupname:</strong>
  <%= @group.groupname %>
</p>

<p>
  <strong>Description:</strong>
  <%= @group.description %>
</p>

<p>
  <strong>Owner name:</strong>
  <%= @group.owner_name %>
</p>

<p>
  <strong>Owner email:</strong>
  <%= @group.owner_email %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @group.owner_id %>
</p>

<p>
  <strong>Is public:</strong>
  <%= @group.is_public %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>
</div>

<br>
<h1>Listing materials</h1>
<div class="span35">
<table class="table table-striped table-hover ">
<tbody> 
<thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Density</th>
      <th>Elastic modulus</th>
      <th>Shear modulus</th>
      <th>Poissons ratio</th>
      <th>Yield strength</th>
      <th>Ultimate tensile strength</th>
      <th>Ultimate total elongation</th>
      <th>Hardness value</th>
      <th>Melting point</th>
      <th>Thermal expansion</th>
      <th>Thermal conductivity</th>
      <th>Specific heat</th>
      <th>Electrical resistivity</th>
      <th>Chemical composition</th>
      <th>Confidence Level</th>
      <th>Show Material</th>
      <% if is_admin? %>
      <th></th>
      <th></th>
      <% end %>
    </tr>
  </thead>

   
    <% @materials.each do |material| %>
      <tr>
        <td><%= material.mat_name %></td>
        <td><%= material.mat_type %></td>
        <td><%= material.density %></td>
	<td><%= material.elastic_modulus %></td>
        <td><%= material.shear_modulus %></td>
        <td><%= material.poissons_ratio %></td>
        <td><%= material.yield_strength %></td>
        <td><%= material.ultimate_tensile_strength %></td>
        <td><%= material.ultimate_total_elongation %></td>
        <td><%= material.hardness_value %></td>
        <td><%= material.melting_point %></td>
        <td><%= material.thermal_expansion %></td>
        <td><%= material.thermal_conductivity %></td>
        <td><%= material.specific_heat %></td>
        <td><%= material.electrical_resistivity %></td>
        <td><%= material.chemical_composition %></td>
	<td><%= material.confidence_level %></td>
	<td><%= link_to 'Show', material, class: "btn btn-large btn-primary"  %></td>
	<% if is_admin? %>        
        <td><%= link_to 'Edit', edit_material_path(material) %></td>
        <td><%= link_to 'Destroy', material, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<% end %>
	<% @files_groups = Testfile.where(:mat_name => material.mat_name) %>
	<% @groups = @files_groups.select(:groupname).uniq %>
	<% @groups.each do |grp| %>
	<td>Group with Testfile</td>
	<th><%= grp.groupname %></th>
	<% end %>
	
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>
<p align="right">
  Export this table to:
  <%= link_to "CSV File", materials_path(format: "csv"), class: "btn btn-large btn-primary"  %> |
  <%= link_to "Excel File", materials_path(format: "xls"), class: "btn btn-large btn-primary"  %>
</p>
<br>
<% if is_admin? or is_group_admin? %> 
<p><h4><%= link_to 'Add New Material to group', new_mat_membership_path %></h4></p>
<% end %>


<h1>Listing testfiles</h1>
<div class="span35">
<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Filename</th>
      <th>Download File</th>
      <th>File Type</th>
      <th>Material Name</th>
      <th>Group Name</th>
      <th>Comments</th>
      <th>Uploaded by</th>
      <th>Person in Charge</th>
      <th>Test Location</th>
      <th>Test Date</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @testfiles.each do |testfile| %>
      <tr>
	<td><%= link_to File.basename(testfile.filename.url), testfile.filename_url %></td> 
	<td><%= link_to 'Download File', :action => 'download', :controller => 'testfiles', :id => testfile.id %></td>       
	<td><%= testfile.file_type %></td>	
	<td><%= testfile.mat_name %></td>	
	<td><%= testfile.groupname %></td>
	<td><%= testfile.comments %></td>
        <td><%= testfile.uploaded_by %></td>
	<td><%= testfile.person_in_charge %></td>
	<td><%= testfile.test_location %></td>
	<td><%= testfile.test_date %></td>
	<td><%= testfile.created_at %></td>
	<td><%= testfile.updated_at %></td>
        <td><%= link_to 'Show', testfile %></td>
	<% if is_admin? or (testfile.person_in_charge == current_user.name) or (testfile.uploaded_by == current_user.name) %>
        <td><%= link_to 'Edit', edit_testfile_path(testfile) %></td>
        <td><%= link_to 'Destroy', testfile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% if is_admin? or is_group_admin? %>
<%= link_to 'New Testfile', new_testfile_path %>
<% end %>
</div>
<br>
<h4><%= link_to 'New Testfile', new_testfile_path %></h4>