config/routes.rb
CapstoneHonda::Application.routes.draw do
  
  resources :dpms
  resources :properties
  resources :password_resets
  resources :testfiles
  
  match '/testfiles/download', :controller => 'testfiles', :action => 'download', via: 'get'
  match '/materials/download', :controller => 'materials', :action => 'download', via: 'get'
  match '/signup', to: 'users#new',           via: 'get'
  match '/signin', to: 'sessions#new',        via: 'get'
  match '/signout',to: 'sessions#destroy',    via: 'delete'
  match '/help',   to: 'static_pages#help',   via: 'get'
  match '/about_path',  to: 'static_pages#about',  via: 'get'
  match '/contact',  to: 'static_pages#contact',  via: 'get'
  match '/users',  to: 'users#index',  via: 'get'
  match '/users/join_group', :controller => 'users', :action => 'join_group', via: 'get'
  match '/users/accept_membership', :controller => 'users', :action => 'accept_membership', via: 'get'

  match '/step1', to: 'dpms#step1', via: 'patch'
  match '/step1', to: 'dpms#step1', via: 'put'
  match '/step1', to: 'dpms#step1', via: 'get'
  match '/step2', to: 'dpms#step2', via: 'patch'
  match '/step2', to: 'dpms#step2', via: 'put'

  match '/step3', to: 'dpms#step3', via: 'patch'
  match '/step3', to: 'dpms#step3', via: 'put'

  match '/step4', to: 'dpms#step4', via: 'patch'
  match '/step4', to: 'dpms#step4', via: 'put'

  resources :materials do
    get :reset_filterrific, :on => :collection
  end

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  root 'static_pages#home'
 
 

  

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :testfiles, :foreign_key => :user_id
  has_many :materials, :foreign_key => :user_id
  attr_accessible :name, :email, :remember_token, :avatar, :password, :password_confirmation
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6, :allow_blank => true }
  mount_uploader :avatar, AvatarUploader

  #This method is associated with password reset, it generates a pw reset token
  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  #returns a randomly generated token for sessions and password recovery
  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  #create a new token for session cookies
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  #encryps token (saved for password_digest and remember_token)
  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    #this will give the user a session token to be saved in cookies 
    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end

end
0

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update, :show, :index]
  before_action :correct_user, only: [:edit, :update, :show]
  def show
     @user = User.find(params[:id])
     @materials = @user.materials
     @testfiles = @user.testfiles
  end

  def new
    if signed_in?
	redirect_to current_user
    else
     @user = User.new
    end
  end

  def edit
  end

  def index
	@user = User.find_by_id(current_user[:id])
	if @user.id<=5
		@users = User.all
	else
		redirect_to current_user, :notice => "You dont have the appropriate permission to view that page!"
	end
  end

  def update
    if @user.update_attributes(user_params)
       flash[:success] = "Profile updated"
       redirect_to @user
    else 
       render 'edit', :notice => "Error updating profile try again!"
    end
  end

  def create
     @user = User.new(user_params)

       if @user.save
          sign_in @user
          flash[:success] = "Welcome #{@user.name}"
           redirect_to @user
       else 
          render 'new'
     end
  end

private 

    def user_params
       params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar, :testfiles, :materials)
    end
    
    def signed_in_user
        #store_location
        #redirect_to signin_url, notice: "PLease sign in." unless signed_in?
    end
    def correct_user
      @user = User.find(params[:id])
      redirect_to(current_user, :notice => "You tried to access a wrong link, please try again!") unless current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/edit.html.erb
<div style="width: 100%; align:center; margin: 0 auto">
<div class="container">
	<div class="col-lg-6"><h1>Update Profile</h1>
  		<div class="well">
    <%= form_for(@user, :class => "bs-example form-horizontal") do |f| %>
	<% if @user.errors.any? %>    	
	<%= render 'shared/error_messages', object: f.object %>
	<% end %>	
	<div class="form-group">
	      	  <%= f.label :name, class: "col-lg-2 control-label" %>
		  <div class="col-lg-10">
		  	<%= f.text_field :name, class: "form-control", placeholder: "Name" %>
		  </div>
	</div>      
	<div class="form-group">
	      	  <%= f.label :email, class: "col-lg-2 control-label" %>
		  <div class="col-lg-10">
		    	<%= f.text_field :email, class: "form-control", placeholder: "Email" %>
		  </div>
	</div>
	
	<div class="form-group">
	      	  <%= f.label :password, class: "col-lg-2 control-label" %>
		  <div class="col-lg-10">
		    	<%= f.password_field :password, class: "form-control", placeholder: "Password" %>
		  </div>
	</div>
      <div class="form-group">
	      	  <%= f.label :password_confirmation, class: "col-lg-2 control-label" %>
		  <div class="col-lg-10">
		    	<%= f.password_field :password_confirmation, class: "form-control", placeholder: "Password" %>
		  </div>
	</div>

      
	<div class="form-group">
		<div class="col-lg-3  col-lg-offset-2">
                    		
			<%= f.submit "Update", class: "btn btn-large btn-primary" %>
		</div>
		<div class="col-lg-3  col-lg-offset-2">
		<%= button_tag "Cancel", :type => 'button', :class => "btn btn-large btn-primary", :onclick => "location.href = '#{user_path}'" %>
		</div>
	</div>
	<% end %>
	
    </div>
  </div>
</div>
</div>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Password</th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.password %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete,
                                     data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="container", align="center">
	<div class="col-lg-6", align="center"><h1>Sign up</h1>
  		<div class="well", align="center">

	 
    <%= form_for(@user, :class => "bs-example form-horizontal", :html => {:multipart => true}) do |f| %>
	<% if @user.errors.any? %>    	
	<%= render 'shared/error_messages', object: f.object %>
	<% end %>	
	<div class="form-group">
	      	  		<%= f.label :name, class: "col-lg-2 control-label" %>
		  		<div class="col-lg-10">
		    			<%= f.text_field :name, class: "form-control", placeholder: "Name" %>
		  		</div>
	</div>     
	<div class="form-group">
	      	  		<%= f.label :email, class: "col-lg-2 control-label" %>
		  		<div class="col-lg-10">
		    			<%= f.text_field :email, class: "form-control", placeholder: "Email" %>
		  		</div>
	</div>
	<div class="form-group">
	      	  		<%= f.label :password, class: "col-lg-2 control-label" %>
		  		<div class="col-lg-10">
		    			<%= f.password_field :password, class: "form-control", placeholder: "Password" %>
		  		</div>
	</div>
	<div class="form-group">
	      	  		<%= f.label :password_confirmation, class: "col-lg-2 control-label" %>
		  		<div class="col-lg-10">
		    			<%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm Password" %>
		  		</div>
	</div>
	<div class="form-group">
		<div class="col-lg-3  col-lg-offset-2">      		
			<%= f.submit "Sign Up", class: "btn btn-large btn-primary" %>
			<%= button_tag "Cancel", :type => 'button', :class => "btn btn-large btn-primary", :onclick => "location.href = '#{root_path}'" %>
		</div>
	</div>
      <p>Already a member? <%= link_to "Login", signin_path %></p>
	<% end %>
	
    </div>
  </div>
</div>
</div>

app/views/users/show.html.erb
<div class="jumbotron">
		<span style="float: left; margin-right: 15px;">
    	<%= image_tag(@user.avatar_url.to_s, :size => "200x200") %>
    </span>
		<h1><%= @user.name %></h1>
		<h3><%= @user.email %></h3>
		<p>This is your Dashboard! Choose what you want to do:</p>
		<% if is_admin? %>
			<p>DEBUG: YOU ARE ADMIN</p>
		<% end %>
		<%= button_to 'Edit Profile', edit_user_path %>
		<h2> Your testfiles </h2>
		<% if @testfiles.any? %>
			<table class="table table-striped table-hover ">
 			<thead>
    		<tr>
      			<th>Filename</th>
      			<th>File Type</th>
      			<th>Material Name</th>
      			<th>Material Type</th>
      			<th>Time Added</th>
      			<th>Date Added</th>
      			<th>Comments</th>
      			<th></th>
      			<% if is_admin? %>
      			<th></th>
      			<th></th>
      			<% end %>
    		</tr>
  			</thead>

  			<tbody>
    			<% @testfiles.each do |testfile| %>
      			<tr>
				<td><%= link_to File.basename(testfile.filename.url), testfile.filename_url %></td>        
				<td><%= testfile.file_type %></td>	
				<td><%= testfile.mat_name %></td>	
  				<td><%= testfile.material.mat_type %></td>
  				<td><p><%= testfile.created_at.strftime("%l:%M:%S %p") %></p></td>
  				<td><p><%= testfile.created_at.strftime("%m/%d/%y") %></p></td>
  				<td><%= testfile.comments %></td>
        		<td><%= link_to 'Edit', edit_testfile_path(testfile) %></td>
        		<td><%= link_to 'Delete', testfile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      			</tr>
    			<% end %>
  			</tbody>

			</table>
			<br>
		<% end %>

		<h2> Your materials </h2>
		<%if @materials.any? %>
			<table class="table table-striped table-hover ">
 			<thead>
    		<tr>
      			<th>Material Name</th>
      			<th>Material Type</th>
      			<th>Time Addded</th>
      			<th>Date Added</th>
      			<th></th>
      			<% if is_admin? %>
      			<th></th>
      			<th></th>
      			<% end %>
    		</tr>
  			</thead>

  			<tbody>
    			<% @materials.each do |material| %>
      		<tr>        
      		<td><%= material.mat_name %></td>	
  				<td><%= material.mat_type %></td>
  				<td><p><%= material.created_at.strftime("%l:%M:%S %p") %></p></td>
  				<td><p><%= material.created_at.strftime("%m/%d/%y") %></p></td>
  				<% if is_admin? %>
        		<td><%= link_to 'Edit', edit_material_path(material) %></td>
        		<td><%= link_to 'Delete', material, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      			</tr>
      			<% end %>
    			<% end %>
  			</tbody>

			</table>
		<% end %>
</div>
<br>