config/routes.rb
CapstoneHonda::Application.routes.draw do
  
  resources :dpms
  resources :properties
  resources :password_resets
  resources :testfiles
  
  match '/testfiles/download', :controller => 'testfiles', :action => 'download', via: 'get'
  match '/materials/download', :controller => 'materials', :action => 'download', via: 'get'
  match '/signup', to: 'users#new',           via: 'get'
  match '/signin', to: 'sessions#new',        via: 'get'
  match '/signout',to: 'sessions#destroy',    via: 'delete'
  match '/help',   to: 'static_pages#help',   via: 'get'
  match '/about_path',  to: 'static_pages#about',  via: 'get'
  match '/contact',  to: 'static_pages#contact',  via: 'get'
  match '/users',  to: 'users#index',  via: 'get'
  match '/users/join_group', :controller => 'users', :action => 'join_group', via: 'get'
  match '/users/accept_membership', :controller => 'users', :action => 'accept_membership', via: 'get'

  match '/step1', to: 'dpms#step1', via: 'patch'
  match '/step1', to: 'dpms#step1', via: 'put'
  match '/step1', to: 'dpms#step1', via: 'get'
  match '/step2', to: 'dpms#step2', via: 'patch'
  match '/step2', to: 'dpms#step2', via: 'put'

  match '/step3', to: 'dpms#step3', via: 'patch'
  match '/step3', to: 'dpms#step3', via: 'put'

  match '/step4', to: 'dpms#step4', via: 'patch'
  match '/step4', to: 'dpms#step4', via: 'put'

  resources :materials do
    get :reset_filterrific, :on => :collection
  end

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  root 'static_pages#home'
 
 

  

end

app/models/material.rb
class Material < ActiveRecord::Base
	validates :mat_name, :presence => true

	validates :mat_type, :inclusion => { :in => ['Liquid', 'Metal', 'Misc', 'Mixture', 'Plastic', 'Rubber'],
    :message => "%{value} is not a valid type" }

	validates_uniqueness_of :mat_name, scope: [:mat_type]
  belongs_to :user
	has_many :testfiles, :foreign_key => :material_id, dependent: :destroy
  has_one :property, dependent: :destroy
	
	attr_accessible :mat_name, :mat_type, :testfiles, :description, :user_id
	
	filterrific(
  	:default_settings => { :sorted_by => 'id_asc' },
  	:filter_names => [:search_query,:sorted_by,:direction_order,:with_created_at_gte,:with_mat_type,:col_name,:range_query]
	)

	def self.to_csv(options = {})
		CSV.generate(options) do |csv|
			csv << column_names
			all.each do |material|
			  csv << material.attributes.values_at(*column_names)
			end
		end
	end

  self.per_page = 100

  scope :search_query, lambda { |query|
    return nil  if query.blank?
    # condition query, parse into individual keywords
    terms = query.downcase.split(/\s+/)
    # replace "*" with "%" for wildcard searches,
    # append '%', remove duplicate '%'s
    terms = terms.map { |e|
      (e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }
    # configure number of OR conditions for provision
    # of interpolation arguments. Adjust this if you
    # change the number of OR conditions.
    num_or_conditions = 2
    where(
      terms.map {
        or_clauses = [
          "LOWER(materials.mat_name) LIKE ?",
          "LOWER(materials.mat_type) LIKE ?"
        ].join(' OR ')
        "(#{ or_clauses })"
      }.join(' AND '),
      *terms.map { |e| [e] * num_or_conditions }.flatten
    )
  }


  def self.options_for_order
	[
	   ['asc'],
	   ['desc']
	]
  end

  scope :col_name, lambda { |colname|
	@@column = colname.to_s
	case colname.to_s
	when /^desc$/
		Material.col_name(session[:filterrific_materials].col_name.to_s)
	else
		order("materials.#{ colname.to_s } asc")
	end
    }
 

  scope :direction_order, lambda { |direction|
	Material.col_name('desc')
  }

  
  
  scope :sorted_by, lambda { |sort_option| 
    # extract the sort direction from the param value.
    direction = (sort_option =~ /asc$/) ? 'asc' : 'desc'
    case sort_option.to_s
    when /^id_/
      order("materials.id #{ direction }")
    when /^created_at_/
      order("materials.created_at #{ direction }")
    when /^mat_name_/
      order("LOWER(materials.mat_name) #{ direction }")
    else
      raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
  }
  
  scope :with_created_at_gte, lambda { |ref_date|
    where('materials.created_at >= ?', ref_date)
  }
  
  scope :sorted_by_type, lambda { |sort_option_type|
    # extract the sort direction from the param value.
    direction = (sort_option_type =~ /desc$/) ? 'desc' : 'asc'
    case sort_option_type.to_s
    when /^type_/
      order("materials.type")
    else
      raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
  }

  scope :with_mat_type, lambda { |mat_type|
    where(:mat_type => [*mat_type])
  }
  
  def self.options_for_sorted_by
    [
	['Name (a-z)', 'mat_name_asc'],
	['Registration date (newest first)', 'created_at_desc'],
	['Registration date (oldest first)', 'created_at_asc'],
	  ]
  end
  
  def self.options_for_sorted_by_type
    [
      ['Liquid'],
      ['Metal'],
      ['Misc'],
      ['Mixture'],
      ['Plastic'],
      ['Rubber']
    ]
  end
  
  

  def decorated_created_at
    created_at.to_date.to_s(:long)
  end

end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :set_material, only: [:show, :edit, :update, :destroy]
#before_action :check_access, only: [:edit, :update, :create, :new, :destroy]

  # GET /materials
  # GET /materials.json
  def index
    @filterrific = Filterrific.new(Material, params[:filterrific] || session[:filterrific_materials])
    @materials = Material.filterrific_find(@filterrific).page(params[:page])
    session[:filterrific_materials] = @filterrific.to_hash

    respond_to do |format|
	  format.html
	  format.js
	  format.csv { render text: @materials.to_csv }
	  format.xls # { send_data @materials.to_csv(col_sep: "\t") }
    end
  end
  
  def reset_filterrific
    session[:filterrific_materials] = nil
    redirect_to :action => :index
  end

  # GET /materials/1
  # GET /materials/1.json
  def show
	  @testfiles = @material.testfiles
  end

  # GET /materials/new
  def new
    @material = Material.new
  end

  # GET /materials/1/edit
  def edit
  end

  # POST /materials
  # POST /materials.json
  def create
    @material = Material.new(material_params)
    property = @material.build_property(:material_id => @material.id)
    @user = User.find_by_id(current_user[:id])
    @user.materials << @material
    #testfiles = @material.testfiles.build(:material_id => @material.id)

    respond_to do |format|
      if @material.save
        format.html { redirect_to @material, notice: 'Material was successfully created.' }
        format.json { render action: 'show', status: :created, location: @material }
      else
        format.html { render action: 'new' }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materials/1
  # PATCH/PUT /materials/1.json
  def update
    respond_to do |format|
      if @material.update(material_params)
        format.html { redirect_to @material, notice: 'Material was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materials/1
  # DELETE /materials/1.json
  def destroy
    @material.destroy

    #find(:all, :conditions => ["name LIKE ? AND active = ?", "%#{search}%", 1])
   respond_to do |format|
      format.html { redirect_to materials_url }
      format.json { head :no_content }
    end
  end
    
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material
      @material = Material.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def material_params
      params.require(:material).permit(:mat_name, :mat_type, :testfiles, :description, :user_id)
    end

    def check_access
	if not (is_admin?)
		if signed_in?
			redirect_to(current_user, :notice => "You tried to access a wrong link, please try again!")
		else
			redirect_to(root, :notice => "You tried to access a wrong link, please try again!")
		end
	end
    end
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/views/materials/_form.html.erb
<!--new material addition page -->
<%= form_for(@material) do |f| %>
  <% if @material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@material.errors.count, "error") %> prohibited this material from being saved:</h2>

      <ul>
      <% @material.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :material %><br>
    <%= f.text_field :mat_name %>
  </div>
  <div class="field">
    <%= f.label :mat_type %><br>
    <%= f.select :mat_type, options_for_select(['Select One', 'Liquid', 'Metal', 'Misc', 'Mixture', 'Plastic', 'Rubber']) %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/materials/_list.html.erb
<div id="filterrific_results">
	<div>
	    <%= page_entries_info materials %>
	</div>
	<div class="span36">
		<table class="table table-striped table-hover ">
		<tbody> 
		<thead>
		    <tr>
		      <th>Name</th>
		      <th>Type</th>
		      <th>Description</th>
		      <th>Yield Strength</th>
		      <th>Ultimate Tensile Strength</th>
		      <th>Added By</th>
		      <th>Date Added</th>
		      <th></th>
		    </tr>
		</thead>

		   
		    <% @materials.each do |material| %>
		    <tr>
			<td><%= material.mat_name %></td>
			<td><%= material.mat_type %></td>
			<td><%= material.description %></td>
			<td><%= material.property.yield_strength %></td>
			<td><%= material.property.ultimate_tensile_strength %></td>
			<td><%= material.user.name %></td>
			<td>
					<p><%= material.created_at.strftime("%H:%M:%S") %></p>
					<p><%= material.created_at.strftime("%m/%d/%y") %></p>
			</td>
			<td><%= link_to 'Testfiles', material, class: "btn btn-large btn-primary"  %>
				<% if is_admin? %>        
				<%= link_to 'Edit', edit_material_path(material), class: "btn btn-large btn-primary" %>
				<%= link_to 'Destroy', material, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-large btn-primary" %>
			</td>
			<% end %>
			<% @files_groups = Testfile.where(:mat_name => material.mat_name) %>
			
		
		      </tr>
		    <% end %>
		  </tbody>
		</table>
	</div>
	<div data-positio="top">
	<%= will_paginate materials %>
	</div>
	<br>
	<h4>
	<il>
	<%= link_to 'Add New Material', new_material_path, class: "btn btn-large btn-primary" %>
	</il>
	<il style="float: right;">
	Export this table to:
	  <%= link_to "CSV File", materials_path(format: "csv"), class: "btn btn-large btn-primary"  %> |
	  <%= link_to "Excel File", materials_path(format: "xls"), class: "btn btn-large btn-primary"  %>
	</il>
	</h4>
</div>

app/views/materials/edit.html.erb
<h1>Editing material</h1>

<%= render 'form' %>

<%= link_to 'Show', @material %> | <%= link_to 'Back', materials_path %>

app/views/materials/index.html.erb
<h1>Listing materials</h1>
  		

<div class="well">
  <%= form_for(@filterrific) do |f| %>
    <div class="row">
           
	<div class="col-lg-2">
	  <%= f.label :Search_Name %>
	  <%= f.text_field :search_query, :class => 'filterrific-periodically-observed' %>
	</div>
	<div class="col-lg-2">
		  <%= f.label :Sort_By_Type %>
		  <%= f.select :with_mat_type, Material.options_for_sorted_by_type, { :include_blank => '- Any -' } %>
	</div>
	<div class="col-lg-4">
	  <%= f.label :Sorted_By %>
	  <%= f.select :sorted_by, Material.options_for_sorted_by %>
	</div>
	
	<div class="col-lg-2">
	   <%= link_to('Reset filters', reset_filterrific_materials_path, class: "btn btn-large btn-primary") %>
  	</div>
  	<%# add an automated spinner to your form when the list is refreshed %>
  	<%= render_filterrific_spinner %>
    <% end %> 
    </div>
</div>

<div id="results">
<%= render :partial => 'materials/list', :locals => { :materials => @materials } %>
</div>

<script>
  
  $('.js-datepicker').datepicker();
  $('#overlayTrigger').click(function(event) {
    event.preventDefault();
    $('body').chardinJs('start');
  });
</script>

app/views/materials/index.js.erb
<%# app/views/students/index.js.erb %>
<% js = escape_javascript(
  render(:partial => 'materials/list', :locals => { :materials => @materials })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/materials/index.xls.erb
<table class="table table-striped table-hover ">
<tbody> 
<thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Density (g/cm<sup>3</sup>)</th>
      <th>Elastic modulus (MPa)</th>
      <th>Shear modulus (MPa)</th>
      <th>Poissons ratio</th>
      <th>Yield strength (MPa)</th>
      <th>Ultimate tensile strength (MPa)</th>
      <th>Ultimate total elongation (%)</th>
      <th>Hardness value</th>
      <th>Melting point (°C)</th>
      <th>Thermal expansion</th>
      <th>Thermal conductivity (W/m-K)</th>
      <th>Specific heat (J/g-°C)</th>
      <th>Electrical resistivity (ohm-cm)</th>
      <th>Chemical composition</th>
      <th>Confidence Level</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

   
    <% @materials.each do |material| %>
      <tr>
        <td><%= material.mat_name %></td>
        <td><%= material.mat_type %></td>
        <td><%= material.density %></td>
	<td><%= material.elastic_modulus %></td>
        <td><%= material.shear_modulus %></td>
        <td><%= material.poissons_ratio %></td>
        <td><%= material.yield_strength %></td>
        <td><%= material.ultimate_tensile_strength %></td>
        <td><%= material.ultimate_total_elongation %></td>
        <td><%= material.hardness_value %></td>
        <td><%= material.melting_point %></td>
        <td><%= material.thermal_expansion %></td>
        <td><%= material.thermal_conductivity %></td>
        <td><%= material.specific_heat %></td>
        <td><%= material.electrical_resistivity %></td>
        <td><%= material.chemical_composition %></td>
	<td><%= material.confidence_level %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/materials/new.html.erb
<h1>New material</h1>

<%= render 'form' %>

<%= button_to 'Back', materials_path%>

app/views/materials/show.html.erb
<div class="jumbotron">
<p>
  <strong>Name:</strong>
  <%= @material.mat_name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @material.mat_type %>
</p>
<p>
  <strong>Description:</strong>
  <%= @material.description %>
</p>
  <div>
    <%= link_to "Material Properties", @material.property%>
  </div>

<% if is_admin? %>
<%= link_to 'Edit', edit_material_path(@material), class: "btn btn-large btn-primary" %>
<% end %>
<%= link_to 'Back', materials_path, class: "btn btn-large btn-primary" %>

</div>
<%= link_to 'Add Testfile', new_testfile_path, class: "btn btn-large btn-primary" %>
<% if @testfiles.any? %>
<h1>Listing testfiles</h1>

<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Filename</th>
      <th>File Type</th>
      <th>Material Name</th>
      <th>Material Type</th>
      <th>Date Added</th>
      <th>Added By</th>
      <th>Comments</th>
      <th></th>
      <% if is_admin? %>
      <th></th>
      <th></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @testfiles.each do |testfile| %>
      <tr>
	<td><%= link_to File.basename(testfile.filename.url), testfile.filename_url %></td>        
	<td><%= testfile.file_type %></td>	
	<td><%= testfile.mat_name %></td>	
  <td><%= testfile.material.mat_type %></td>
  <td>
          <p><%= testfile.created_at.strftime("%H:%M:%S") %></p>
          <p><%= testfile.created_at.strftime("%m/%d/%y") %></p>
  </td>
  <td><%= testfile.user.name %></td>
  <td><%= testfile.comments %></td>
	<% if is_admin? %>
        <td><%= link_to 'Edit', edit_testfile_path(testfile) %></td>
        <td><%= link_to 'Delete', testfile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<% end %>
      </tr>
    <% end %>
  </tbody>

</table>
<br>

<% end %>